### ISSUE TITLE
Issue with npm run commit as core is not at 90% test coverage. 

### ISSUE THREAD

**Issue by bhatnagarm** [sotekton/agnostic#12]
ERROR: Coverage for lines (66.67%) does not meet threshold (90%) for /Users/mitulbhatnagar/mituls_workspace/NodeJS/apps-merge/tap.js
ERROR: Coverage for branches (33.33%) does not meet threshold (50%) for /Users/mitulbhatnagar/mituls_workspace/NodeJS/apps-merge/tap.js
ERROR: Coverage for branches (12.5%) does not meet threshold (50%) for /Users/mitulbhatnagar/mituls_workspace/NodeJS/apps-merge/core/apps-merge/get/mergeFlights.js
ERROR: Coverage for lines (25%) does not meet threshold (90%) for /Users/mitulbhatnagar/mituls_workspace/NodeJS/apps-merge/core/index.js
ERROR: Coverage for functions (11.11%) does not meet threshold (50%) for /Users/mitulbhatnagar/mituls_workspace/NodeJS/apps-merge/core/index.js
ERROR: Coverage for branches (0%) does not meet threshold (50%) for /Users/mitulbhatnagar/mituls_workspace/NodeJS/apps-merge/core/index.js
ERROR: Coverage for statements (21.43%) does not meet threshold (50%) for /Users/mitulbhatnagar/mituls_workspace/NodeJS/apps-merge/core/index.js
husky > pre-commit hook failed (add --no-verify to bypass)
Mituls-MacBook-Pro:apps-merge mitulbhatnagar$ git commit -am "Commit for further development." --no-verify
[mock-aircrews 9d061c3] Commit for further development.
 9 files changed, 163 insertions(+), 239 deletions(-)
 delete mode 100644 microgen/core.js
 delete mode 100644 microgen/core.spec.js
 delete mode 100644 microgen/shell.js
 delete mode 100644 microgen/shell.schema.js

**Comment by Keidrych** [comment]
100% core coverage
